// <auto-generated />
using System;
using Festify.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Festify.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251029175928_new-entity-category")]
    partial class newentitycategory
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Festify.Data.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(547),
                            Description = "...",
                            IsActive = true,
                            Name = "Desserts"
                        },
                        new
                        {
                            ID = 2,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(548),
                            Description = "...",
                            IsActive = true,
                            Name = "Main Dish"
                        });
                });

            modelBuilder.Entity("Festify.Data.Models.City", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("CountryId");

                    b.HasIndex("Name", "CountryId")
                        .IsUnique();

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CountryId = 1,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(465),
                            IsActive = true,
                            Name = "Sarajevo"
                        },
                        new
                        {
                            ID = 2,
                            CountryId = 1,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(466),
                            IsActive = true,
                            Name = "Mostar"
                        },
                        new
                        {
                            ID = 3,
                            CountryId = 1,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(466),
                            IsActive = true,
                            Name = "Banja Luka"
                        },
                        new
                        {
                            ID = 4,
                            CountryId = 1,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(467),
                            IsActive = true,
                            Name = "Jajce"
                        },
                        new
                        {
                            ID = 5,
                            CountryId = 1,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(467),
                            IsActive = true,
                            Name = "Trebinje"
                        },
                        new
                        {
                            ID = 6,
                            CountryId = 2,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(468),
                            IsActive = true,
                            Name = "Paris"
                        },
                        new
                        {
                            ID = 7,
                            CountryId = 2,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(468),
                            IsActive = true,
                            Name = "Lyon"
                        },
                        new
                        {
                            ID = 8,
                            CountryId = 2,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(469),
                            IsActive = true,
                            Name = "Nice"
                        },
                        new
                        {
                            ID = 9,
                            CountryId = 2,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(469),
                            IsActive = true,
                            Name = "Cannes"
                        },
                        new
                        {
                            ID = 10,
                            CountryId = 2,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(470),
                            IsActive = true,
                            Name = "Marseille"
                        },
                        new
                        {
                            ID = 11,
                            CountryId = 3,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(470),
                            IsActive = true,
                            Name = "Berlin"
                        },
                        new
                        {
                            ID = 12,
                            CountryId = 3,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(471),
                            IsActive = true,
                            Name = "Munich"
                        },
                        new
                        {
                            ID = 13,
                            CountryId = 3,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(471),
                            IsActive = true,
                            Name = "Hamburg"
                        },
                        new
                        {
                            ID = 14,
                            CountryId = 3,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(472),
                            IsActive = true,
                            Name = "Cologne"
                        },
                        new
                        {
                            ID = 15,
                            CountryId = 3,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(472),
                            IsActive = true,
                            Name = "Frankfurt"
                        },
                        new
                        {
                            ID = 16,
                            CountryId = 4,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(473),
                            IsActive = true,
                            Name = "Venice"
                        },
                        new
                        {
                            ID = 17,
                            CountryId = 4,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(473),
                            IsActive = true,
                            Name = "Rome"
                        },
                        new
                        {
                            ID = 18,
                            CountryId = 4,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(474),
                            IsActive = true,
                            Name = "Milan"
                        },
                        new
                        {
                            ID = 19,
                            CountryId = 4,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(474),
                            IsActive = true,
                            Name = "Florence"
                        },
                        new
                        {
                            ID = 20,
                            CountryId = 4,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(475),
                            IsActive = true,
                            Name = "Turin"
                        },
                        new
                        {
                            ID = 21,
                            CountryId = 5,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(475),
                            IsActive = true,
                            Name = "Oslo"
                        },
                        new
                        {
                            ID = 22,
                            CountryId = 5,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(476),
                            IsActive = true,
                            Name = "Bergen"
                        },
                        new
                        {
                            ID = 23,
                            CountryId = 5,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(476),
                            IsActive = true,
                            Name = "Tromsø"
                        },
                        new
                        {
                            ID = 24,
                            CountryId = 5,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(477),
                            IsActive = true,
                            Name = "Stavanger"
                        },
                        new
                        {
                            ID = 25,
                            CountryId = 5,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(477),
                            IsActive = true,
                            Name = "Trondheim"
                        },
                        new
                        {
                            ID = 26,
                            CountryId = 6,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(478),
                            IsActive = true,
                            Name = "Lisbon"
                        },
                        new
                        {
                            ID = 27,
                            CountryId = 6,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(478),
                            IsActive = true,
                            Name = "Porto"
                        },
                        new
                        {
                            ID = 28,
                            CountryId = 6,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(479),
                            IsActive = true,
                            Name = "Faro"
                        },
                        new
                        {
                            ID = 29,
                            CountryId = 6,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(479),
                            IsActive = true,
                            Name = "Coimbra"
                        },
                        new
                        {
                            ID = 30,
                            CountryId = 6,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(480),
                            IsActive = true,
                            Name = "Braga"
                        },
                        new
                        {
                            ID = 31,
                            CountryId = 7,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(480),
                            IsActive = true,
                            Name = "Barcelona"
                        },
                        new
                        {
                            ID = 32,
                            CountryId = 7,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(481),
                            IsActive = true,
                            Name = "Madrid"
                        },
                        new
                        {
                            ID = 33,
                            CountryId = 7,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(481),
                            IsActive = true,
                            Name = "Seville"
                        },
                        new
                        {
                            ID = 34,
                            CountryId = 7,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(482),
                            IsActive = true,
                            Name = "Valencia"
                        },
                        new
                        {
                            ID = 35,
                            CountryId = 7,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(482),
                            IsActive = true,
                            Name = "Bilbao"
                        },
                        new
                        {
                            ID = 36,
                            CountryId = 8,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(483),
                            IsActive = true,
                            Name = "Istanbul"
                        },
                        new
                        {
                            ID = 37,
                            CountryId = 8,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(483),
                            IsActive = true,
                            Name = "Ankara"
                        },
                        new
                        {
                            ID = 38,
                            CountryId = 8,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(484),
                            IsActive = true,
                            Name = "Izmir"
                        },
                        new
                        {
                            ID = 39,
                            CountryId = 8,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(484),
                            IsActive = true,
                            Name = "Antalya"
                        },
                        new
                        {
                            ID = 40,
                            CountryId = 8,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(485),
                            IsActive = true,
                            Name = "Bodrum"
                        },
                        new
                        {
                            ID = 41,
                            CountryId = 9,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(485),
                            IsActive = true,
                            Name = "London"
                        },
                        new
                        {
                            ID = 42,
                            CountryId = 9,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(486),
                            IsActive = true,
                            Name = "Edinburgh"
                        },
                        new
                        {
                            ID = 43,
                            CountryId = 9,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(516),
                            IsActive = true,
                            Name = "Manchester"
                        },
                        new
                        {
                            ID = 44,
                            CountryId = 9,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(517),
                            IsActive = true,
                            Name = "Bristol"
                        },
                        new
                        {
                            ID = 45,
                            CountryId = 9,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(517),
                            IsActive = true,
                            Name = "Brighton"
                        },
                        new
                        {
                            ID = 46,
                            CountryId = 10,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(518),
                            IsActive = true,
                            Name = "New Orleans"
                        },
                        new
                        {
                            ID = 47,
                            CountryId = 10,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(518),
                            IsActive = true,
                            Name = "Austin"
                        },
                        new
                        {
                            ID = 48,
                            CountryId = 10,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(519),
                            IsActive = true,
                            Name = "New York"
                        },
                        new
                        {
                            ID = 49,
                            CountryId = 10,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(519),
                            IsActive = true,
                            Name = "Los Angeles"
                        },
                        new
                        {
                            ID = 50,
                            CountryId = 10,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(520),
                            IsActive = true,
                            Name = "Miami"
                        });
                });

            modelBuilder.Entity("Festify.Data.Models.Country", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Flag")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(447),
                            IsActive = true,
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            ID = 2,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(447),
                            IsActive = true,
                            Name = "France"
                        },
                        new
                        {
                            ID = 3,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(448),
                            IsActive = true,
                            Name = "Germany"
                        },
                        new
                        {
                            ID = 4,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(448),
                            IsActive = true,
                            Name = "Italy"
                        },
                        new
                        {
                            ID = 5,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(449),
                            IsActive = true,
                            Name = "Norway"
                        },
                        new
                        {
                            ID = 6,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(449),
                            IsActive = true,
                            Name = "Portugal"
                        },
                        new
                        {
                            ID = 7,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(450),
                            IsActive = true,
                            Name = "Spain"
                        },
                        new
                        {
                            ID = 8,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(450),
                            IsActive = true,
                            Name = "Turkey"
                        },
                        new
                        {
                            ID = 9,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(450),
                            IsActive = true,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            ID = 10,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(451),
                            IsActive = true,
                            Name = "United States"
                        });
                });

            modelBuilder.Entity("Festify.Data.Models.Gender", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(436),
                            IsActive = true,
                            Name = "Male"
                        },
                        new
                        {
                            ID = 2,
                            CreatedAt = new DateTime(2025, 10, 29, 17, 59, 27, 997, DateTimeKind.Utc).AddTicks(436),
                            IsActive = true,
                            Name = "Female"
                        });
                });

            modelBuilder.Entity("Festify.Data.Models.MyAppUser", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenderId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUser")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LockoutUntil")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("CityId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GenderId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("MyAppUsers");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CityId = 2,
                            CreatedAt = new DateTime(2026, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "example1@gmail.com",
                            FailedLoginAttempts = 0,
                            FirstName = "Denis",
                            GenderId = 1,
                            IsActive = true,
                            IsAdmin = true,
                            IsUser = false,
                            LastName = "Mušić",
                            PasswordHash = "IgMYwzB6X5PuYBmawgLgpI9yvs6hBXyjMsbSsekdN78=",
                            PasswordSalt = "LW1OrdymeTyhGY+mZtAX1n+7lT+6KeiC5V+OBYDxo1M=",
                            PhoneNumber = "+387 00 000 000",
                            Username = "admin"
                        },
                        new
                        {
                            ID = 2,
                            CityId = 2,
                            CreatedAt = new DateTime(2026, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "example2@gmail.com",
                            FailedLoginAttempts = 0,
                            FirstName = "Adil",
                            GenderId = 1,
                            IsActive = true,
                            IsAdmin = false,
                            IsUser = true,
                            LastName = "Joldić",
                            PasswordHash = "ZveHSuFlPVMq1PfKAIbSEwOCvru5aREntG+5TwLfG9k=",
                            PasswordSalt = "BGi8INa959tQtpm8LcUNtG9wEYFrhzAwrbYCC8I40OU=",
                            PhoneNumber = "+387 00 000 000",
                            Username = "user"
                        },
                        new
                        {
                            ID = 3,
                            CityId = 1,
                            CreatedAt = new DateTime(2026, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "hana.haljevac@edu.fit.com",
                            FailedLoginAttempts = 0,
                            FirstName = "Hana",
                            GenderId = 2,
                            IsActive = true,
                            IsAdmin = true,
                            IsUser = false,
                            LastName = "Heljevac",
                            PasswordHash = "UPv2Fk73/0jhr3jBkqPdcma5ercKY97a3kAGm+gh2oA=",
                            PasswordSalt = "sL8mF4ZFomnGdoN7tlIYOL/j3MjmNquASbH1LNeTHiE=",
                            PhoneNumber = "+387 00 000 000",
                            Username = "hana"
                        },
                        new
                        {
                            ID = 4,
                            CityId = 2,
                            CreatedAt = new DateTime(2026, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "aida.patak@edu.fit.com",
                            FailedLoginAttempts = 0,
                            FirstName = "Aida",
                            GenderId = 2,
                            IsActive = true,
                            IsAdmin = false,
                            IsUser = true,
                            LastName = "Patak",
                            PasswordHash = "vClg9ZMsFfEDwvsOtuKcSHTD3ZEFQbkbT1uiT3z4LqM=",
                            PasswordSalt = "TXV14TzPAbApcdXxF/QtSsHDy+4KlHyUuinfOlz2vvs=",
                            PhoneNumber = "+387 00 000 000",
                            Username = "aida"
                        });
                });

            modelBuilder.Entity("Festify.Data.Models.MyAuthenticationToken", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MyAppUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("MyAppUserId");

                    b.ToTable("MyAuthenticationTokens");
                });

            modelBuilder.Entity("Festify.Data.Models.City", b =>
                {
                    b.HasOne("Festify.Data.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Festify.Data.Models.MyAppUser", b =>
                {
                    b.HasOne("Festify.Data.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Festify.Data.Models.Gender", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("Festify.Data.Models.MyAuthenticationToken", b =>
                {
                    b.HasOne("Festify.Data.Models.MyAppUser", "MyAppUser")
                        .WithMany()
                        .HasForeignKey("MyAppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MyAppUser");
                });
#pragma warning restore 612, 618
        }
    }
}
